export const pcsxcfg = `Bios = SET_BY_PCSX
Gpu3 = builtin_gpu
Spu = builtin_spu
Xa = 0
Mdec = 0
Cdda = 0
Debug = 0
PsxOut = 0
SpuIrq = 0
RCntFix = 0
VSyncWA = 0
Cpu = 0
region = 0
g_scaler3 = 2
g_gamma = 64
g_layer_x = 0
g_layer_y = 0
g_layer_w = 0
g_layer_h = 0
soft_filter = 0
scanlines = 0
scanline_level = 14
plat_target.vout_method = 1
plat_target.hwfilter = 0
plat_target.vout_fullscreen = 0
state_slot = 0
cpu_clock = ffffffff
g_opts = 00
in_type_sel1 = 0
in_type_sel2 = 0
analog_deadzone = 32
memcard1_sel = ffffffff
memcard2_sel = ffffffff
g_autostateld_opt = 0
open_invalid_time = 16
adev0_is_nublike = 0
adev1_is_nublike = 0
frameskip3 = 0
gpu_peops.iUseDither = 0
gpu_peops.dwActFixes = 80
gpu_unai.lineskip = 0
gpu_unai.abe_hack = 0
gpu_unai.no_light = 0
gpu_unai.no_blend = 0
gpu_neon.allow_interlace = 2
gpu_neon.enhancement_enable = 0
gpu_neon.enhancement_no_main = 0
gpu_peopsgl.bDrawDither = 0
gpu_peopsgl.iFilterType = 0
gpu_peopsgl.iFrameTexType = 0
gpu_peopsgl.iUseMask = 0
gpu_peopsgl.bOpaquePass = 0
gpu_peopsgl.bAdvancedBlend = 0
gpu_peopsgl.bUseFastMdec = 0
gpu_peopsgl.iVRamSize = 40
gpu_peopsgl.iTexGarbageCollection = 1
gpu_peopsgl.dwActFixes = 0
spu_config.iUseReverb = 1
spu_config.iXAPitch = 0
spu_config.iUseInterpolation = 1
spu_config.iTempo = 0
spu_config.iUseThread = 1
config_save_counter = 4
in_evdev_allow_abs_only = 0
volume_boost = 0
psx_clock = 39
new_dynarec_hacks = 0
in_enable_vibration = 0
binddev = sdl:keys
bind escape = Enter Menu
bind backspace = Fast Forward
bind c = player1 SELECT
bind d = player1 TRIANGLE
bind e = player1 L2
bind r = player1 R1
bind s = player1 SQUARE
bind t = player1 R2
bind v = player1 START
bind w = player1 L1
bind x = player1 CIRCLE
bind z = player1 CROSS
bind f1 = Save State
bind f2 = Load State
bind f3 = Prev Save Slot
bind f4 = Next Save Slot
bind f5 = Toggle Frameskip
bind f6 = Take Screenshot
bind f7 = Show/Hide FPS
bind f8 = Switch Renderer
bind f9 = CD Change button
bind f10 = RESET button
bind f11 = Toggle fullscreen
bind right = player1 RIGHT
bind left = player1 LEFT
bind down = player1 DOWN
bind up = player1 UP
bind eject = CD Change button
bind reset = RESET button
binddev = sdl:Sony Interactive Entertainment Controller
bind escape = Enter Menu
bind backspace = Fast Forward
bind f1 = Save State
bind f2 = Load State
bind f3 = Prev Save Slot
bind f4 = Next Save Slot
bind f5 = Toggle Frameskip
bind f6 = Take Screenshot
bind f7 = Show/Hide FPS
bind f8 = Switch Renderer
bind f9 = CD Change button
bind f10 = RESET button
bind f11 = Toggle fullscreen
bind right = player1 RIGHT
bind left = player1 LEFT
bind down = player1 DOWN
bind up = player1 UP
bind \\xF0 = player1 TRIANGLE
bind \\xF1 = player1 CIRCLE
bind \\xF2 = player1 CROSS
bind \\xF3 = player1 SQUARE
bind \\xF4 = player1 L2
bind \\xF5 = player1 R2
bind \\xF6 = player1 L1
bind \\xF7 = player1 R1
bind \\xF8 = player1 SELECT
bind \\xF9 = player1 START
bind eject = CD Change button
bind reset = RESET button
binddev = sdl:Sony Interactive Entertainment Controller [1]
bind escape = Enter Menu
bind backspace = Fast Forward
bind f1 = Save State
bind f2 = Load State
bind f3 = Prev Save Slot
bind f4 = Next Save Slot
bind f5 = Toggle Frameskip
bind f6 = Take Screenshot
bind f7 = Show/Hide FPS
bind f8 = Switch Renderer
bind f9 = CD Change button
bind f10 = RESET button
bind f11 = Toggle fullscreen
bind right = player2 RIGHT
bind left = player2 LEFT
bind down = player2 DOWN
bind up = player2 UP
bind \\xF0 = player2 TRIANGLE
bind \\xF1 = player2 CIRCLE
bind \\xF2 = player2 CROSS
bind \\xF3 = player2 SQUARE
bind \\xF4 = player2 L2
bind \\xF5 = player2 R2
bind \\xF6 = player2 L1
bind \\xF7 = player2 R1
bind \\xF8 = player2 SELECT
bind \\xF9 = player2 START
bind eject = CD Change button
bind reset = RESET button
binddev = sdl:Sony SCPH-1000R
bind escape = Enter Menu
bind backspace = Fast Forward
bind f1 = Save State
bind f2 = Load State
bind f3 = Prev Save Slot
bind f4 = Next Save Slot
bind f5 = Toggle Frameskip
bind f6 = Take Screenshot
bind f7 = Show/Hide FPS
bind f8 = Switch Renderer
bind f9 = CD Change button
bind f10 = RESET button
bind f11 = Toggle fullscreen
bind right = player1 RIGHT
bind left = player1 LEFT
bind down = player1 DOWN
bind up = player1 UP
bind \\xF0 = player1 TRIANGLE
bind \\xF1 = player1 CIRCLE
bind \\xF2 = player1 CROSS
bind \\xF3 = player1 SQUARE
bind \\xF4 = player1 L2
bind \\xF5 = player1 R2
bind \\xF6 = player1 L1
bind \\xF7 = player1 R1
bind \\xF8 = player1 SELECT
bind \\xF9 = player1 START
bind eject = CD Change button
bind reset = RESET button
binddev = sdl:Sony SCPH-1000R [1]
bind escape = Enter Menu
bind backspace = Fast Forward
bind f1 = Save State
bind f2 = Load State
bind f3 = Prev Save Slot
bind f4 = Next Save Slot
bind f5 = Toggle Frameskip
bind f6 = Take Screenshot
bind f7 = Show/Hide FPS
bind f8 = Switch Renderer
bind f9 = CD Change button
bind f10 = RESET button
bind f11 = Toggle fullscreen
bind right = player2 RIGHT
bind left = player2 LEFT
bind down = player2 DOWN
bind up = player2 UP
bind \\xF0 = player2 TRIANGLE
bind \\xF1 = player2 CIRCLE
bind \\xF2 = player2 CROSS
bind \\xF3 = player2 SQUARE
bind \\xF4 = player2 L2
bind \\xF5 = player2 R2
bind \\xF6 = player2 L1
bind \\xF7 = player2 R1
bind \\xF8 = player2 SELECT
bind \\xF9 = player2 START
bind eject = CD Change button
bind reset = RESET button
binddev = sdl:iBUFFALO BSGP1204 Series
bind escape = Enter Menu
bind backspace = Fast Forward
bind f1 = Save State
bind f2 = Load State
bind f3 = Prev Save Slot
bind f4 = Next Save Slot
bind f5 = Toggle Frameskip
bind f6 = Take Screenshot
bind f7 = Show/Hide FPS
bind f8 = Switch Renderer
bind f9 = CD Change button
bind f10 = RESET button
bind f11 = Toggle fullscreen
bind right = player1 RIGHT
bind left = player1 LEFT
bind down = player1 DOWN
bind up = player1 UP
bind \\xF0 = player1 TRIANGLE
bind \\xF1 = player1 CIRCLE
bind \\xF2 = player1 CROSS
bind \\xF3 = player1 SQUARE
bind \\xF4 = player1 L2
bind \\xF5 = player1 R2
bind \\xF6 = player1 L1
bind \\xF7 = player1 R1
bind \\xF8 = player1 SELECT
bind \\xF9 = player1 START
bind eject = CD Change button
bind reset = RESET button
binddev = sdl:iBUFFALO BSGP1204 Series [1]
bind escape = Enter Menu
bind backspace = Fast Forward
bind f1 = Save State
bind f2 = Load State
bind f3 = Prev Save Slot
bind f4 = Next Save Slot
bind f5 = Toggle Frameskip
bind f6 = Take Screenshot
bind f7 = Show/Hide FPS
bind f8 = Switch Renderer
bind f9 = CD Change button
bind f10 = RESET button
bind f11 = Toggle fullscreen
bind right = player2 RIGHT
bind left = player2 LEFT
bind down = player2 DOWN
bind up = player2 UP
bind \\xF0 = player2 TRIANGLE
bind \\xF1 = player2 CIRCLE
bind \\xF2 = player2 CROSS
bind \\xF3 = player2 SQUARE
bind \\xF4 = player2 L2
bind \\xF5 = player2 R2
bind \\xF6 = player2 L1
bind \\xF7 = player2 R1
bind \\xF8 = player2 SELECT
bind \\xF9 = player2 START
bind eject = CD Change button
bind reset = RESET button
`;

export const placeholderImage64 = `iVBORw0KGgoAAAANSUhEUgAAAOIAAADiCAIAAADccoyAAAAJrUlEQVR4nO3caU8aXwOG8WHABRVFRGttXSoqSmyaNE3T7//GD9C4gdYtNuKCogKCLM+Lyd8QZhFx8Okt1++FITge6OGSM8yMDWxsbBjAv838fz8B4HlkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgFkCgGh7g2dz+evr6/v7+/L5XKtVms0GoFAwDTN/v7+oaGh0dHRWCwWCrX7BPwdrVwuX19f5/P5h4eHSqVSq9WsocLhcDQajcfjwWCw03/3azFvdoGNjQ3fBy2VSvv7+/f3996bBYPBjx8/fv78+S1He3x8PD09zWazjUbDbZu+vr65ubnJyUnvoXzHvLnxP9N8Pr+7u1uv19vcPhqNJpPJQCDwBqOVSqXt7e1KpdLOUJ8+fZqdnW3zcV+PefPg877pw8NDOp1uf3YMw7i5uTk8PHyD0crl8tbWVptzbRjG6enpxcWFxwbFYnF7e7tarXpsU61Wt7a2SqWS92P11Lx1wOdMDw8Pa7XaS3/q/Py8WCx2e7S9vb3Hx8cXDXV8fOxWodVoPp/f2dlxC6JWq21vb9/e3j5bau/MW2f8zLRUKt3c3Dh+a25u7ufPn6urq457641G4/z8vKujXV5e3t3d2TceHR39/v37t2/fBgYG7N99fHy0D2X8twhaL979/b3j8lqr1XZ2dgqFgjWOR6m9M28d8zPT6+trx/vHxsZmZmZM04xGo/Pz847b5PP5ro6WzWbtm5mmuby8bH1Qddudury8bLmnWCxubm42v8Hk8/lMJtP82aJer+/u7ja/wB6l9si8vYafB6Qcf+0Mw4jH40+3o9Go4zblcrl7oz08PDiONj4+3tfXZ90eHR0NhUL9/f0DAwPW18HBQetGy0/VajX7e+f19XUmk1lZWTEMo9FopNPp29vblm3q9brjWtwj8/YafmbquGdjGMbQ0NDT7faPq/k4mr0Yy8jIyNPt/v7+Hz9+tDNaJBJJJpM7Ozsth2Zyudze3l4ikchkMvZl1zTNZDLZ/IhPemTeXsPPTBcWFh7/U6lUrK/VanVwcPBpG7f9s/7+/u6N5vbKNQ/1ImNjY8lkcnd3t6XUy8vL+/v7h4eHlu0DgcDKysro6KjjaL0zbx3zM9Px8fFnt3HbZYlEIt0bzfocY2ctTIVCIZvN3t7eVioV0zQHBgai0eiHDx/sBTSLRqNLS0uZTKblfsdGl5eX3dZZo8fmrTNdPFlqVywWHXfJDcPo4NRF+6O5HfMLhUInJyenp6dP99Tr9Wq1WigUzs7OZmdnp6enPZ7AxMREvV7f39/32CYQCCQSiVgs5rHNs97ZvHXg7S49KZVKbocYI5GI24Loy2huBxFb5rrlRw4PD4+Pj72fxuTk5MLCgscGX758af7s0oF3OW8v9UaZ3t3dbW5uOv52BoPBRCLR1dHcpvvZkyV///599sDK9PS02zo7MTExNTXl/ePe3vG8vchbZHpxceFxUjGRSLxol7yD0TyulnjW0dGR91nHbDbrdqjy6urqNUe53/e8vUjX900PDw/Pzs4cvxUIBJaWll6039bZaKZpuk3Z5OTk3NycaZrZbPbk5MT+wlgnVNx2ti4uLg4ODjye8MHBgWmaHaz773veXqqLmdZqtXQ6bT+xYQkGg96ff30cLRQKOa50IyMjTyvdzMxMqVRyXM5ubm4cp/vq6sr785NhGI1GY39/PxgMtvMB3PLu560D3Vr0rSuD3GYnHA6vr6+3P9evHO3plEmLlh1Htzl1O8O5t7dnv99x6Uyn027n2Vu8+3nrTFfeTSuVyvb2ttuzjMfji4uLptnub8jrRwuHw46HAFtO6Lmd37NfH5TP59PptH2li8fjiURib2/v6uqq+X6r1LW1Nfthzmbvft465v+7abVadZsd0zQXFxeXlpban2tfRhseHm7nsdp8Vnd3d/bzT4ZhxGKxpaUla1fPvsTX6/WdnR2Pa+nf/by9hs8P0Gg0dnd3HWcnGAyurq6+6ACNX6O5HVxsGdl+GYel5bRKIBCwX+VunZR62mB5eXlsbMw+lNvl8b0wb6/hc6YnJyeO19QEg8FUKvXSY9F+jTY8PNx84cWTlpMxbocDW1bqkZGRVCrVfPXG2NjYyspK85uKaZorKyvNl2iEQqFUKuX2/tQL8/Yafv4tVLFY/P37d8cH2379+tW90c7Pz//8+WPfLBaLzc/Ph0Khi4uLo6Mjx4dLJpP2RbxQKFiHIa1qHRc+a+UtFAp9fX1ra2uOL7nRY/PWGT8/QjkeP/tHRpuamspms/YPBLlcLpfLefzg8PCw41wPDw+nUqmjo6Pl5WW3nbNQKLS2tpbJZBYWFsLhsNtD9NS8dca3Rb9cLrd5zOXtR7O86COIxTRNjxOSQ0NDa2tr3n/kbpXq0WgPzlsHfMs0l8v5+Evs72iWcDj8bFXNrD+lcFup/cK8tTWmXwP5+0vs+1uCJRKJfP36tZ3D4yMjI+vr6z4uW26Yt3b4tm/qdgntvzBas4GBgdXV1VKplMvl7u7uSqVStVqt1WqBQCAUCg0ODkYikVgs5vjXIN3AvLWjK/85D+Av/kc+CCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCCBTCPgfRDwOa+6GSyEAAAAASUVORK5CYII=`;
